config/routes.rb
CucsDemo::Application.routes.draw do

  root 'accounts#index'

  resources :accounts, :only => [:index, :withdraw] do
    member do
      post :withdraw
    end
  end

end

app/models/account.rb
class Account < ActiveRecord::Base
	attr_accessor :amount

	scope :with_balance, -> { where('balance > 0') }
	
	validate :valid_amount

	def withdraw
		diff = balance.to_i - amount.to_i
		self.balance = diff
		res = self.save
		reload
		res
	end

	private

	def valid_amount
		errors[:amount] << 'must be more than 0.' if amount.to_i <= 0
		errors[:balance] << 'not enough.' if balance_was.to_i < amount.to_i
	end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

	def index
		@account = Account.with_balance.reload.first # || Account.new
		# @account.balance = 10000 if @account.balance == 0
		# @account.save(:validate => false)
	end

	def withdraw
		@account = Account.find_by_id(params[:id])
		@account.amount = params[:account][:amount].to_i
		if @account.withdraw
			flash[:notice] = 'Successful'
		else
			flash[:error] = "Failure: #{@account.errors.full_messages}"
		end

		render :template => 'accounts/index'
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
module ApplicationHelper

	def flash_message
		f = Marshal.load(Marshal.dump(flash))
		flash.clear
	  f.map do |key, msg|
	    content_tag :div, msg, :id => key, :class => 'flash'
	  end.join

	end
	
end

app/views/accounts/index.html.erb
<h1>My Account</h1>
<%= form_for @account, :url => withdraw_account_url(@account), :method => :post do |f| %>
	<%=raw flash_message %>
	<div>
		<div class="label">Current Balance:&nbsp;</div>
		<div class="field">$ <%= f.text_field :balance, :disabled => true %></field>
	</div>
	<div>
		<div class="label">Enter amount to withdraw:&nbsp;</div>
		<div class="field">$ <%= f.text_field :amount %></div>
	</div>
	<div class="actions">
		<%= f.submit 'OK' %>
		<%= f.button 'Cancel', :id => 'cancelBtn' %>
	</div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CucsDemo</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>